# Generated by Django 4.0.3 on 2022-07-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teams_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='video',
            field=models.FileField(blank=True, upload_to='videos_uploaded'),
        ),
    ]
