# Generated by Django 4.0.3 on 2022-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teams_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='Subject',
            field=models.CharField(default=1, max_length=200, verbose_name='المادة الدراسية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teams',
            name='Abstract',
            field=models.TextField(verbose_name=' السيرة الذاتية'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='Specialization',
            field=models.CharField(choices=[('الابتدائية', 'الابتدائية'), ('الاعدادية', 'الاعدادية'), ('الثانوية', 'الثانوية')], max_length=200, verbose_name='المرحلة الدراسية'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/teams', verbose_name=' الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=50, verbose_name=' اسم المدرس'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='video',
            field=models.FileField(blank=True, upload_to='videos_uploaded', verbose_name=' فيديوا تعريفي'),
        ),
    ]
