# Generated by Django 4.0.3 on 2022-07-28 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0005_alter_teams_image_alter_teams_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=25, verbose_name=' اسم الطالب')),
                ('parent_name', models.CharField(max_length=25, verbose_name=' اسم ولي الامر')),
                ('address', models.CharField(max_length=25, verbose_name='محل الاقامة')),
                ('age', models.IntegerField(verbose_name='محل الاقامة')),
                ('barthdate', models.DateField(verbose_name=' تاريخ الميلاد')),
                ('email', models.CharField(max_length=250, verbose_name='البريد الالكتروني')),
                ('phone', models.CharField(max_length=250, verbose_name=' رقم التلفون')),
                ('comment', models.TextField(verbose_name='ملاحظات ولي الامر')),
                ('card_team', models.ManyToManyField(to='team.teams', verbose_name='المدرسين')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
