# Generated by Django 4.0.3 on 2022-07-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_teams_image_alter_teams_video'),
        ('accounts', '0004_remove_profile_about_me_remove_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_team',
            field=models.ManyToManyField(to='team.teams'),
        ),
    ]
